# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_LA"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = " Linear Algebra and Array-oriented procedures (LICENSE:MIT)"
categories = ["Linear Algebra"]
keywords = ["fortran", "Arrays", "Linear Algebra"]
homepage = "https://github.com/urbanjost/M_LA.git"

#[install]
#library=true

#[[test]]
#name="test_suite"
#source-dir="test"
#main="test_suite_M_LA.f90"
#[test.dependencies]
#M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }

#[[executable]]
#name="mat"
#source-dir="app"
#main="mat.f90"

[dependencies]
#M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
#M_strings      = { git = "https://github.com/urbanjost/M_strings.git" }
#M_CLI2         = { git = "https://github.com/urbanjost/M_CLI2.git" }
#M_list         = { git = "https://github.com/urbanjost/M_list.git" }
